/// Mirrors KAN's Technical Indicators using Git and Code context
#[derive(Debug, Clone)]
pub struct ContextualIndicators {
    pub file_churn_rate: f64,    // 0.0 to 1.0 (how often this file is modified)
    pub test_coverage: f64,      // 0.0 to 1.0
    pub author_seniority: f64,   // 0.0 (intern) to 1.0 (principal)
    pub is_critical_path: bool,  // e.g. auth.rs, crypto.rs
}

/// A pure signal generated by our scanners (e.g. LlmReview, BabylonianSwarm)
#[derive(Debug, Clone)]
pub struct SecuritySignal {
    pub vulnerability_type: String,
    pub confidence: f64,
}

/// A "Crossover" happens when a raw technical signal intersects with high-risk contextual indicators.
/// Inspired by `financial_timeseries_kan.clj` where SMA and RSI crossovers generate buy/sell signals.
pub struct CrossoverDetector {
    pub churn_threshold: f64,
    pub coverage_threshold: f64,
}

impl CrossoverDetector {
    pub fn new() -> Self {
        Self {
            churn_threshold: 0.50, // 50% churn
            coverage_threshold: 0.30, // 30% coverage
        }
    }

    /// Evaluates whether a raw vulnerability signal crosses over the context thresholds to become a TRUE ALERT.
    /// Returns Some(AlertReason) if a crossover triggers, or None if it's filtered out (False Positive).
    pub fn evaluate(&self, signal: &SecuritySignal, context: &ContextualIndicators) -> Option<String> {
        tracing::debug!("Evaluating Signal: {:?} against Context: {:?}", signal, context);

        // 1. Absolute Conviction Crossover (Signal confidence > 0.95 always bypasses filters)
        if signal.confidence > 0.95 {
             return Some(format!(
                 "🚨 ABSOLUTE CROSSOVER: {} (Conf: {:.2})", 
                 signal.vulnerability_type, signal.confidence
             ));
        }
        
        // 2. Volatility Crossover: High Churn + Low Coverage + Any Signal
        if context.file_churn_rate > self.churn_threshold && context.test_coverage < self.coverage_threshold {
            return Some(format!(
                "📉 VOLATILITY CROSSOVER: {} found in highly volatile, untested file! (Churn: {:.2}, Cov: {:.2})", 
                signal.vulnerability_type, context.file_churn_rate, context.test_coverage
            ));
        }

        // 3. Risk Crossover: Critical Path + Junior Author + Any Signal
        if context.is_critical_path && context.author_seniority < 0.3 {
            return Some(format!(
                "🔥 RISK CROSSOVER: {} found in CRITICAL path modified by Junior author!", 
                signal.vulnerability_type
            ));
        }
        
        // Otherwise, the signal is considered a False Positive / Low Priority Noise and is filtered.
        None
    }
}
